---
title: "Enfants_02"
format: html
---

```{r Setup}
#| message: FALSE
#| echo: False

library(tidyverse)
library(questionr)

```

# ENFANTS
# 1. NETTOYAGE PRÉLIMINAIRE

## 1.1 Retirer les colonnes vides et hors module

```{r E4_B0 to E4_B1}

# Importer la base
E4_B0 <- haven::read_sas("/Users/alicethomassin/Documents/Scolarité/Muco 2026/data_hors_git/raw_data/gb_ddb_fa_04_enfants_04.sas7bdat")

# Identifier les colonnes vides
empty_cols_E4_B0 <- E4_B0 %>%
  mutate(across(
    .cols = where(is.character),
    .fns = ~ na_if(., "")
  )) %>%
  summarise(across(everything(), ~ sum(is.na(.)))) %>% 
  pivot_longer(everything(),
               names_to = "variable",
               values_to = "nb_empty_cells") %>% 
  filter(nb_empty_cells == nrow(E4_B0))

# Créer vecteur avec le nom des variables à retirer
vars_vides <- empty_cols_E4_B0$variable

vars_enfant <- E4_B0 %>% 
  select(enfants_sf_enfants, sf_enfants, sf_enf_conjt_prenom,
         sf_enf_prenom, sf_enf_sexe, sf_enf_mois_nais, sf_enf_an_nais,
         sf_enf_issu, sf_enf_mois_adopte, sf_enf_an_adopte, sf_enf_diag_avt,
         sf_enf_muco, sf_enf_decede, sf_enf_mois_deces, sf_enf_an_deces) %>% 
  colnames()

# Retirer les variables, corriger les formats et les NA character
E4_B1 <- E4_B0 %>%
  select(-all_of(vars_vides)) %>% 
  haven::zap_label() %>% 
  haven::zap_formats() %>%
  mutate(across(
    .cols = where(is.character),
    .fns = ~ na_if(., "")
  )) %>% 
  select(-c("tab_db", "id_fa_cat", "id_type", "id_age_cat_2", "id_age_cat_3",
            "fa_type")) %>%
  select(id_date_creation, fa_date_creation, enfants_date_creation, id_anonymat,
         id_sep, id_sexe, id_date_nais, all_of(vars_enfant)) %>% 
  mutate(
    aa_cor = case_when(
      is.na(id_date_nais) ~ 1,
      is.na(id_date_creation) ~ 2,
      TRUE ~ NA_integer_
    )
  ) %>%
  relocate(aa_cor, .after = enfants_date_creation)



 rm(list = c("empty_cols_E4_B0", "vars_vides", "E4_B0", "vars_enfant"))

```

## 1.2 Corriger les problèmes d'importation
```{r}

Couple <- readr::read_csv("/Users/alicethomassin/Documents/Scolarité/Muco 2026/data_hors_git/clean_data/THOA_couple_m2.csv", show_col_types = FALSE)

corrections0 <- E4_B1 %>% 
  filter(aa_cor > 0)

patch <- Couple %>% 
  filter(id_anonymat %in% corrections0$id_anonymat) %>% 
  select(id_date_creation, fa_date_creation, id_anonymat, id_sep, id_sexe, id_date_nais)

corrections1 <- corrections0 %>% 
  rows_upsert(
    patch,
    by = "id_anonymat"
  )
  
E4_B2 <- E4_B1 %>% 
  filter_out(id_anonymat %in% corrections1$id_anonymat) %>% 
  bind_rows(corrections1) %>% 
  arrange(id_anonymat) %>%
  select(-aa_cor)

rm(list = c("corrections0", "corrections1", "patch"))

```

# 2. STANDARDISER LE MODULE
## 2.1 Ajouter tous les enquêtés
```{r}
Famille <- readr::read_csv("/Users/alicethomassin/Documents/Scolarité/Muco 2026/data_hors_git/clean_data/THOA_famille_1.csv", show_col_types = FALSE)

rep_enfants <- Famille %>% 
  select(id_date_creation, fa_date_creation, id_anonymat, id_sep,
         id_date_nais, id_sexe, vrep_enfant = sf_enfants, commentaires_fam,
         sf_enf_bio_nb, sf_enf_adopte_nb)

vars_join <- rep_enfants %>% 
  select(-vrep_enfant, -commentaires_fam, -sf_enf_bio_nb, -sf_enf_adopte_nb) %>% 
  colnames()

E4_T0 <- full_join(
  E4_B2,
  rep_enfants,
  by = vars_join,
  relationship = "many-to-one"
) %>% 
  relocate(vrep_enfant, .after = id_date_nais) %>% 
  mutate(
    vrep_enfant = factor(vrep_enfant)
  ) %>% 
  select(-enfants_sf_enfants, -sf_enfants) %>% 
  relocate(c("sf_enf_bio_nb", "sf_enf_adopte_nb"), .after = vrep_enfant)


```



## 2.2 Identifier ceux qui ont participé

```{r}

# Les variables pour lesquelles la non-réponse doit être comptée
vars_verif <- E4_T0 %>% 
  select(sf_enf_conjt_prenom:sf_enf_an_deces) %>% 
  colnames()

to_factor <- E4_T0 %>% 
  select(id_sexe, sf_enf_sexe, sf_enf_issu, sf_enf_diag_avt, sf_enf_muco,
         sf_enf_decede) %>% 
  colnames()

# Variable qui va nous permettre de savoir qui a complété le module
E4_T1 <- E4_T0 %>%
  mutate(
    nb_NA = rowSums(is.na(across(all_of(vars_verif))))
  ) %>%
  mutate(
    fa_en_complet = case_when(
      id_anonymat == "FCISN" ~ "777",
      nb_NA < length(vars_verif) ~ "1",
      vrep_enfant == 1 & nb_NA == length(vars_verif) ~ "333",
      vrep_enfant == 0 & nb_NA == length(vars_verif) ~ "777",
      is.na(vrep_enfant) & nb_NA == length(vars_verif) ~ "0",
      TRUE ~ "E"
    ),
    fa_en_complet = factor(fa_en_complet, levels = c("0", "1", "333", "777"))
  ) %>%
  relocate(nb_NA, fa_en_complet) %>% 
  mutate(across(all_of(to_factor), as.factor)) %>% 
  mutate(
    fa_en_enfants = case_when(
      fa_en_complet %in% c("1", "333") ~ "1",
      fa_en_complet == "777" ~ "0",
      !is.na(fa_date_creation) & is.na(vrep_enfant) ~ "555",
      is.na(fa_date_creation) & is.na(enfants_date_creation) &
        is.na(vrep_enfant) ~ NA_character_,
      TRUE ~ "E"
    ),
    fa_en_enfants = factor(fa_en_enfants)
  ) %>% 
  relocate(fa_en_enfants, .after = vrep_enfant)


cas_verif <- E4_T1 %>% 
  group_by(id_anonymat) %>% 
  mutate(n = n()) %>% 
  group_by(id_anonymat, fa_en_complet) %>% 
  mutate(check = n()) %>% 
  ungroup() %>% 
  filter(check != n)

correction_check <- cas_verif %>% 
  filter_out(fa_en_complet == 333) %>% 
  slice(-c(4,
           7:8)) %>% 
  mutate(
    sf_enf_bio_nb = replace_when(sf_enf_bio_nb,
                                 id_anonymat == "VNFLB" ~ 2,
                                 id_anonymat == "FIQBG" ~ 3),
    sf_enf_adopte_nb = replace_na(sf_enf_adopte_nb, 0)
  ) %>% 
  select(-check, -n)

E4_T2 <- E4_T1 %>% 
  filter_out(id_anonymat %in% correction_check$id_anonymat) %>% 
  bind_rows(correction_check) %>% 
  filter_out(
    (id_anonymat == "JNDTO" & sf_enf_issu == 1)|
    (id_anonymat == "RICJW" & sf_enf_conjt_prenom == "Mm")
  ) %>% 
  arrange(id_anonymat) %>% 
  mutate(
    sf_enf_conjt_prenom = str_to_upper(sf_enf_conjt_prenom),
    sf_enf_conjt_prenom = replace_when(sf_enf_conjt_prenom,
                                            sf_enf_conjt_prenom == "NA" ~ "NAA"),
         sf_enf_prenom = str_to_upper(sf_enf_prenom)) %>% 
  select(-c("nb_NA", "vrep_enfant"))

rm(list = c("cas_verif", "correction_check", "Couple", "E4_B1", "E4_B2",
            "Famille", "rep_enfants", "to_factor",
            "vars_join", "vars_verif"))

```