---
title: "Fratrie_01"
format: html
---


```{r Setup}
#| message: FALSE
#| echo: False

library(tidyverse)
library(questionr)

```

# 1. NETTOYAGE PRÉLIMINAIRE

## 1.1 Retirer les colonnes vides et hors module

```{r E4_B0 to E4_B1}

# Importer la base
FR_B0 <- haven::read_sas("/Users/alicethomassin/Documents/Scolarité/Muco 2026/data_hors_git/raw_data/gb_ddb_fa_04_fratrie_04.sas7bdat")

# Identifier les colonnes vides
empty_cols_FR_B0 <- FR_B0 %>%
  mutate(across(
    .cols = where(is.character),
    .fns = ~ na_if(., "")
  )) %>%
  summarise(across(everything(), ~ sum(is.na(.)))) %>% 
  pivot_longer(everything(),
               names_to = "variable",
               values_to = "nb_empty_cells") %>% 
  filter(nb_empty_cells == nrow(FR_B0))

# Créer vecteur avec le nom des variables à retirer
vars_vides <- empty_cols_FR_B0$variable

vars_fratrie <- FR_B0 %>% 
  select(sf_fratrie_bio_nb, pf_rang_nais, sf_fratrie_demi_nb, sf_fratrie_adopte_nb,
         pf_fratrie, pf_fratrie_prenom, pf_fratrie_sexe, pf_fratrie_mois_nais,
         pf_fratrie_an_nais, pf_frsr_issu, pf_frsr_mois_adopte, pf_frsr_an_adopte,
         pf_fratrie_diag_avt_nais, pf_fratrie_muco, pf_fratrie_decede,
         pf_fratrie_mois_deces, pf_fratrie_an_deces) %>% 
  colnames()

# Retirer les variables, corriger les formats et les NA character
FR_B1 <- FR_B0 %>%
  select(-all_of(vars_vides)) %>% 
  haven::zap_label() %>% 
  haven::zap_formats() %>%
  mutate(across(
    .cols = where(is.character),
    .fns = ~ na_if(., "")
  )) %>%
  select(id_date_creation, fa_date_creation, fratrie_date_creation, id_anonymat,
         id_sep, id_sexe, id_date_nais, all_of(vars_fratrie)) %>% 
  mutate(
    aa_cor = case_when(
      is.na(id_date_nais) ~ 1,
      is.na(id_date_creation) ~ 2,
      TRUE ~ NA_integer_
    )
  ) %>%
  relocate(aa_cor, .after = fratrie_date_creation)



 rm(list = c("empty_cols_FR_B0", "vars_vides", "FR_B0", "vars_fratrie"))

```
